kind: pipeline
name: rocker/r-ver:latest

steps:
- name: build 'n check
  image: rocker/r-ver:latest
  commands:
  - echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' >> "${R_HOME}/etc/Rprofile.site"
  - echo 'options("repos"="http://cran.rstudio.com", encoding="UTF-8")' > "/home/$USER/.Rprofile"
  - cat "${R_HOME}/etc/Rprofile.site"
  - cat "/home/$USER/.Rprofile"
  - R -e 'install.packages("tinytest", repos="https://cloud.r-project.org")'
  - R CMD build --no-build-vignettes --no-manual .
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - export _R_CHECK_CRAN_INCOMING_=FALSE
  - export _R_CHECK_FORCE_SUGGESTS_=FALSE
  - R CMD check $FILE --no-vignettes --no-manual --as-cran --install-args=--install-tests
