kind: pipeline
name: rocker/r-ubuntu:jammy

steps:
- name: build 'n check
  image: rocker/r-ubuntu:jammy
  commands:
  - R -e 'install.packages("tinytest")'
  - R CMD build --no-build-vignettes --no-manual .
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - export _R_CHECK_CRAN_INCOMING_=FALSE
  - export _R_CHECK_FORCE_SUGGESTS_=FALSE
  - R CMD check $FILE --no-vignettes --no-manual --as-cran --install-args=--install-tests
